// ─── Export helpers (CSV, JSON, clipboard) ────────────────────────────────────

import type { EnrichedTransfer, Analysis, PnlSummary, KinsPrice } from '../types';
import { fmtUsd, fmtKins, fmtPct } from './format';

function dl(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escCsv(v: unknown): string {
  const s = String(v ?? '');
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

// ─── Trade CSV ───────────────────────────────────────────────────────────────

export function exportTradesCsv(transfers: EnrichedTransfer[], wallet: string) {
  const header = [
    'Date', 'Type', 'Amount KINS', 'KINS Price USD', 'USD Value',
    'Price Source', 'Counterparty', 'Signature', 'Solscan',
  ].join(',');

  const rows = transfers.map((t) =>
    [
      escCsv(t.date),
      t.direction === 'in' ? 'Sell/In' : 'Buy/Out',
      t.amount,
      t.kinsPriceAtTx ?? '',
      t.txUsdValue ?? '',
      t.priceSource,
      escCsv(t.counterparty),
      t.signature,
      t.solscan,
    ].join(',')
  );

  dl([header, ...rows].join('\n'), `kintara-trades-${wallet.slice(0, 8)}.csv`, 'text/csv');
}

// ─── Summary JSON ─────────────────────────────────────────────────────────────

export function exportSummaryJson(
  analysis: Analysis,
  pnl: PnlSummary,
  price: KinsPrice | null,
) {
  const payload = {
    wallet: analysis.wallet,
    generatedAt: new Date().toISOString(),
    kinsPriceUsd: price?.priceUsd ?? null,
    summary: analysis.summary,
    pnl,
  };
  dl(
    JSON.stringify(payload, null, 2),
    `kintara-summary-${analysis.wallet.slice(0, 8)}.json`,
    'application/json'
  );
}

// ─── Clipboard report ─────────────────────────────────────────────────────────

export function buildReportText(
  analysis: Analysis,
  pnl: PnlSummary,
  price: KinsPrice | null,
): string {
  const lines = [
    '══════════════════════════════════',
    '  KINTARA LEDGER — WALLET REPORT  ',
    '══════════════════════════════════',
    `Wallet:        ${analysis.wallet}`,
    `Generated:     ${new Date().toUTCString()}`,
    `KINS Price:    ${price ? fmtKins(price.priceUsd, 8) + ' USD' : 'Unavailable'}`,
    '──────────────────────────────────',
    `Total Buy:     ${fmtKins(pnl.totalBuyKins, 4)} KINS  (${fmtUsd(pnl.totalBuyUsd)})`,
    `Total Sell:    ${fmtKins(pnl.totalSellKins, 4)} KINS  (${fmtUsd(pnl.totalSellUsd)})`,
    `Net KINS:      ${pnl.netKins >= 0 ? '+' : ''}${fmtKins(pnl.netKins, 4)}`,
    `Realized P/L:  ${fmtUsd(pnl.realizedProfitUsd)}`,
    `ROI:           ${fmtPct(pnl.roiPercent)}`,
    `Buy count:     ${analysis.summary.buyCount}`,
    `Sell count:    ${analysis.summary.sellCount}`,
    '──────────────────────────────────',
    `Price source:  ${pnl.hasHistoricalPrices ? 'GeckoTerminal historical' : 'current price only'}`,
    'Generated by Kintara Ledger',
  ];
  return lines.join('\n');
}
